//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef SPAWNDEV_NANOFRAMEWORK_WEBRTC_H
#define SPAWNDEV_NANOFRAMEWORK_WEBRTC_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_SpawnDev_nanoFramework_WebRTC_SpawnDev_nanoFramework_WebRTC_PeerConnection
{
    NANOCLR_NATIVE_DECLARE(Create___STATIC__I4__STRING);
    NANOCLR_NATIVE_DECLARE(CreateOffer___STATIC__VOID__I4);
    NANOCLR_NATIVE_DECLARE(SetRemoteDescription___STATIC__VOID__I4__STRING);
    NANOCLR_NATIVE_DECLARE(AddIceCandidate___STATIC__VOID__I4__STRING);
    NANOCLR_NATIVE_DECLARE(GetLocalSdpLength___STATIC__I4__I4);
    NANOCLR_NATIVE_DECLARE(GetLocalSdp___STATIC__VOID__I4__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(CreateDataChannel___STATIC__I4__I4__STRING__I4__I4);
    NANOCLR_NATIVE_DECLARE(GetChannelId___STATIC__I4__I4__STRING);
    NANOCLR_NATIVE_DECLARE(Send___STATIC__I4__I4__I4__SZARRAY_U1__I4);
    NANOCLR_NATIVE_DECLARE(TryReceive___STATIC__I4__I4__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(GetState___STATIC__I4__I4);
    NANOCLR_NATIVE_DECLARE(GetStat___STATIC__I4__I4__I4);
    NANOCLR_NATIVE_DECLARE(Close___STATIC__VOID__I4);

    //--//
};

struct Library_SpawnDev_nanoFramework_WebRTC_SpawnDev_nanoFramework_WebRTC_TrackerSignaling
{
    static const int FIELD___ws = 1;
    static const int FIELD___url = 2;
    static const int FIELD___rootCaPem = 3;
    static const int FIELD___allowUnverified = 4;

    //--//
};

struct Library_SpawnDev_nanoFramework_WebRTC_SpawnDev_nanoFramework_WebRTC_WebSocketClient
{
    static const int FIELD___socket = 1;
    static const int FIELD___tls = 2;
    static const int FIELD___rng = 3;
    static const int FIELD___one = 4;
    static const int FIELD___open = 5;
    // renamed backing field '<LastError>k__BackingField'
    static const int FIELD__LastError = 6;

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SpawnDev_nanoFramework_WebRTC;

#endif // SPAWNDEV_NANOFRAMEWORK_WEBRTC_H
